### ISSUE TITLE
Broken steps at "Exercise 2 Task 2 - Use the InkCanvas control in the application"

### ISSUE THREAD

**Issue by runceel** [Microsoft/AppConsult-WinAppsModernizationWorkshop#24]
I found a broken steps like following image. Step 8 is empty.

![image](https://user-images.githubusercontent.com/79868/56789276-7f9f8d00-683c-11e9-8db9-661075b6ffa8.png)

And in my case, the Exception written at step 7 didn't occur.

**Comment by qmatteoq** [comment]
Fixed with #26
