### ISSUE TITLE
COMException ocurred at end of Exercise 4.

### ISSUE THREAD

**Issue by runceel** [Microsoft/AppConsult-WinAppsModernizationWorkshop#46]
When selecting same date on the CalenderViewWrapper control, then following error is occurred.

![image](https://user-images.githubusercontent.com/79868/57105687-49508a80-6ce0-11e9-8158-a37ee355ff8c.png)

I think that you need the length check before accessing AddedDates property at the SelectedDatesChanged event handler like below:

```cs
private void CalendarView_SelectedDatesChanged(CalendarView sender, CalendarViewSelectedDatesChangedEventArgs args)
{
    // Add using System.Linq;
    if (args.AddedDates.Any())
    {
        SelectedDate = args.AddedDates[0];
    }
}
```

**Comment by qmatteoq** [comment]
Fixed in 6781dd0
